/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 RocketThrust.glb --t 
*/
import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Thrust: THREE.Mesh
  }
  materials: {
    M_White: THREE.MeshPhysicalMaterial
  }
}

export function Model(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF(import.meta.env.BASE_URL + 'RocketThrust.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Thrust.geometry} material={materials.M_White} rotation={[0, 0, -0.428]} scale={0.365} />
    </group>
  )
}

export default Model

useGLTF.preload(import.meta.env.BASE_URL + 'RocketThrust.glb')