/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 WebsiteRocket.glb --t
*/
import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane001: THREE.Mesh
    Plane001_1: THREE.Mesh
    Plane001_2: THREE.Mesh
  }
  materials: {
    M_RedTip: THREE.MeshPhysicalMaterial
    M_White: THREE.MeshPhysicalMaterial
    M_GreyThruster: THREE.MeshPhysicalMaterial
  }
}

export function Model(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF(import.meta.env.BASE_URL + 'WebsiteRocket.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane001.geometry} material={materials.M_RedTip} />
      <mesh geometry={nodes.Plane001_1.geometry} material={materials.M_White} />
      <mesh geometry={nodes.Plane001_2.geometry} material={materials.M_GreyThruster} />
    </group>
  )
}

useGLTF.preload(import.meta.env.BASE_URL + 'WebsiteRocket.glb')
