/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 hourglass.glb -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import type { ThreeElements } from '@react-three/fiber'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Hourglass001: THREE.Mesh
    HourglassGlass001: THREE.Mesh
  }
  materials: {
    ['Material.004']: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export function Model(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/Hourglass.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Hourglass001.geometry} material={materials['Material.004']} scale={0.735} />
      <mesh geometry={nodes.HourglassGlass001.geometry} material={materials['Material.004']} scale={0.804} />
    </group>
  )
}

useGLTF.preload('/Hourglass.glb')
